package_assets: off
javascripts:
  app:
    - public/javascripts/jquery.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/application.js
    - public/javascripts/models/*.js
    - public/javascripts/**/*.js
    - app/views/**/*.jst
  jquery:
    - public/javascripts/jquery-ui-1.8.16.custom.js

stylesheets:
  jquery: 
    - public/stylesheets/jquery-ui-1.8.16.custom.css
